buildscript {
    repositories {
        mavenCentral()
        maven {
           url = 'https://repo.grails.org/grails/restricted'
        }
        maven {
           url = 'https://repository.apache.org/content/groups/snapshots'
           content {
              includeVersionByRegex('org[.]apache[.]grails.*', '.*', '.*-SNAPSHOT')
           }
           content {
              includeVersionByRegex('org[.]apache[.]groovy.*', 'groovy.*', '.*-SNAPSHOT')
           }
           mavenContent {
              snapshotsOnly()
           }
        }
        maven {
           url = 'https://repository.apache.org/content/groups/staging'
           content {
              includeVersionByRegex('org[.]apache[.]grails[.]gradle', 'grails-publish', '.*')
           }
           content {
              includeVersionByRegex('org[.]apache[.]groovy.*', 'groovy.*', '.*')
           }
           mavenContent {
              releasesOnly()
           }
        }
    }
    dependencies { // Not Published to Gradle Plugin Portal
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-data-hibernate5"
        classpath "org.apache.grails:grails-data-hibernate5-dbmigration"
        classpath "org.apache.grails:grails-gradle-plugins"
    }
}

plugins {
    id "war"
    id "idea"
    id "eclipse"
}

// Not Published to Gradle Plugin Portal
apply plugin: "org.apache.grails.gradle.grails-web"
apply plugin: "org.apache.grails.gradle.grails-gson"

group = "example"

repositories {
    mavenCentral()
    maven {
       url = 'https://repo.grails.org/grails/restricted'
    }
    maven {
       url = 'https://repository.apache.org/content/groups/snapshots'
       content {
          includeVersionByRegex('org[.]apache[.]grails.*', '.*', '.*-SNAPSHOT')
       }
       content {
          includeVersionByRegex('org[.]apache[.]groovy.*', 'groovy.*', '.*-SNAPSHOT')
       }
       mavenContent {
          snapshotsOnly()
       }
    }
    maven {
       url = 'https://repository.apache.org/content/groups/staging'
       content {
          includeVersionByRegex('org[.]apache[.]grails[.]gradle', 'grails-publish', '.*')
       }
       content {
          includeVersionByRegex('org[.]apache[.]groovy.*', 'groovy.*', '.*')
       }
       mavenContent {
          releasesOnly()
       }
    }
}

dependencies {
    profile "org.apache.grails.profiles:rest-api"
    developmentOnly "org.springframework.boot:spring-boot-devtools" // Spring Boot DevTools may cause performance slowdowns or compatibility issues on larger applications
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-data-hibernate5"
    implementation "org.apache.grails:grails-data-hibernate5-dbmigration"
    implementation "org.apache.grails:grails-data-mongodb-gson-templates"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails:grails-events"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-views-gson"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-tomcat"
    console "org.apache.grails:grails-console"
    runtimeOnly "com.zaxxer:HikariCP"
    runtimeOnly "org.postgresql:postgresql"
    testImplementation "org.apache.grails:grails-testing-support-datamapping"
    testImplementation "org.apache.grails:grails-testing-support-views-gson"
    testImplementation "org.mockito:mockito-core"
    testImplementation "org.spockframework:spock-core"
    testImplementation "org.testcontainers:postgresql"
    testImplementation "org.testcontainers:spock"
    testImplementation "org.testcontainers:testcontainers"
}

compileJava.options.release = 21

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

